"""Every checkable claim on the front page, checked, and written before the page existed.

Four kinds of claim, following the contract this toolset shares:

    NUMBER     a figure on the page against the measurement that produced it
    COMMAND    a command the page offers against what CI actually runs
    OUTPUT     a quoted block, line by line, against the transcript it names
    REFERENCE  every link and path against what exists

Plus the one this repository needs and the others do not: a VOCABULARY check. Every claim here
is bounded, and a page that says a rule prevents or eliminates anything has stopped describing
what was measured.
"""

from __future__ import annotations

import json
import pathlib
import re
from typing import Any

import pytest
import yaml

REPO = pathlib.Path(__file__).resolve().parents[1]
README = (REPO / "README.md").read_text(encoding="utf-8")
EVIDENCE = REPO / "docs" / "evidence"


def evidence(name: str) -> dict[str, Any]:
    loaded: dict[str, Any] = json.loads(
        (EVIDENCE / name / "summary.json").read_text(encoding="utf-8")
    )
    return loaded


def own_prose() -> str:
    """The page minus the generated cross-link footer, which describes other repositories."""
    start, end = "<!-- toolset:start -->", "<!-- toolset:end -->"
    if start in README and end in README:
        return README[: README.index(start)] + README[README.index(end) + len(end) :]
    return README


def test_the_numbers_on_the_page_are_the_measured_ones() -> None:
    """NUMBER, recomputed from the registry and the incident rather than from a note."""
    from quietz.monitors import REGISTRY

    incident = evidence("incident")
    claims = {
        "monitors in the registry": str(len(REGISTRY)),
        "alert firings": str(incident["alert_firings_posted"]),
        "notifications delivered": str(incident["notifications_delivered"]),
    }
    missing = {name: value for name, value in claims.items() if value not in README}
    assert missing == {}, f"the README no longer states these measured figures: {missing}"


def test_the_page_says_which_way_this_repository_fails() -> None:
    """The decision that runs against the grain of every sibling, stated where a reader meets it."""
    flattened = " ".join(own_prose().split()).lower()
    assert "fail" in flattened and "open" in flattened
    assert "most silent exactly when something is most wrong" in flattened


def test_the_page_says_what_each_mechanism_actually_did() -> None:
    """THE ROW, NOT THE PAGE. A page this long contains any small integer somewhere, so the
    figure is read out of the row that carries it.

    The table used to describe what the three mechanisms do in general and present all three as
    producing the measured gap. Grouping produced none of it: inhibition removes the completeness
    alert before grouping sees it and the survivors route to different receivers, so the replay
    could never have carried two alerts in one notification. The counterfactual under the table
    said the opposite, which is the sentence an interviewer is most likely to probe.
    """
    incident = evidence("incident")
    rows = {
        "deduplication": {incident["evaluations"], 1},
        "grouping": {incident["max_alerts_in_one_notification"]},
    }
    for label, expected in rows.items():
        row = next(
            (line for line in own_prose().splitlines() if line.startswith(f"| {label} |")), None
        )
        assert row, f"the page no longer has a row for {label}, so it explains one mechanism less"
        stated = {int(number) for number in re.findall(r"\b\d+\b", row)}
        assert stated == expected, (
            f"the {label} row states {sorted(stated)} and the replay measured {sorted(expected)}: "
            f"{row}"
        )


def test_no_large_number_on_the_page_is_one_nothing_measured() -> None:
    """A stale copy of a figure elsewhere on the page."""
    incident = evidence("incident")
    measured = {
        incident["alert_firings_posted"],
        incident["notifications_delivered"],
    }
    written = {
        int(token.replace(",", "")) for token in re.findall(r"\b\d{1,3}(?:,\d{3})+\b", README)
    }
    invented = sorted(written - measured)
    assert invented == [], f"the page states {invented}, which nothing here produces"


def test_every_command_the_page_offers_is_one_ci_runs() -> None:
    """COMMAND. Except the four that run inside the shared workflow, which is named.

    Checked against CONTRIBUTING.md as well as README.md, because CONTRIBUTING.md makes the
    stronger claim: it says its own command list is "read out of `.github/workflows/ci.yml`
    when this file is generated". Five of its eight commands are not literally in that file,
    they run inside the shared workflow this repository does not contain, so that sentence
    overclaims a mechanism nothing here can verify. CONTRIBUTING.md is generated by a tool
    outside this repository and a hand edit to its prose is erased on the next run, so this
    check does not try to fix the sentence; it makes sure the commands themselves, which
    nothing checked before, never drift from what CI actually runs.
    """
    workflow = yaml.safe_load((REPO / ".github" / "workflows" / "ci.yml").read_text("utf-8"))
    executed = "\n".join(
        line
        for job in workflow["jobs"].values()
        for step in job.get("steps", [])
        if isinstance(step.get("run"), str)
        for line in step["run"].splitlines()
        if not line.strip().startswith("#")
    )
    shared = "PNX89/.github/.github/workflows/checks.yml"
    assert shared in (REPO / ".github" / "workflows" / "ci.yml").read_text("utf-8")
    delegated = ("uv run pytest", "uv run ruff", "uv run mypy", "uv sync")

    pages = {
        "the README": README,
        "CONTRIBUTING.md": (REPO / "CONTRIBUTING.md").read_text(encoding="utf-8"),
    }
    for label, text in pages.items():
        offered = re.findall(r"^\s*(?:\$ )?(uv run [^\n]+|scripts/\S+)$", text, re.MULTILINE)
        assert offered, f"{label} offers no command at all"
        for command in offered:
            command = command.strip()
            if command.startswith(delegated):
                continue
            assert command in executed, f"{label} offers `{command}` and CI never runs it"


def test_every_block_quoted_from_a_transcript_is_in_that_transcript() -> None:
    """OUTPUT, line by line, against the file each block names in an HTML comment."""
    blocks = re.findall(r"<!-- quoted from (\S+) -->\n```text\n(.*?)```", README, re.S)
    assert blocks, "no block on the page declares where it was quoted from"
    for path, body in blocks:
        source = REPO / path
        assert source.exists(), f"the page quotes {path}, which does not exist"
        lines = {line.strip() for line in source.read_text("utf-8").splitlines()}
        for line in body.splitlines():
            if line.strip():
                assert line.strip() in lines, (
                    f"the page quotes {line.strip()!r} as coming from {path}, and it is not there"
                )


def test_every_path_and_link_on_the_page_exists() -> None:
    """REFERENCE, including the paths written as inline code."""
    targets = set(re.findall(r"\]\((?!https?:)([^)#]+)", README))
    targets |= {
        found
        for found in re.findall(r"`([a-zA-Z0-9_./-]+)`", README)
        if "/" in found and not found.startswith(("http", "-"))
    }
    missing = sorted(target for target in targets if not (REPO / target.strip()).exists())
    assert missing == [], f"the README points at paths that do not exist: {missing}"


#: Phrases this repository must not CLAIM. Some belong to a sibling and some overclaim, and the
#: check below is about the claim rather than the word: a page saying it is NOT an on-call
#: rotation is doing the right thing, and a blanket ban would fail it for saying so.
CLAIMS_TO_AVOID = (
    "in production",
    "at scale",
    "on call for",
    "incident response",
    "uptime",
)

#: Vocabulary belonging to a sibling repository. These are banned outright, negation or not,
#: because using a sibling's phrase even to disclaim it is still describing its subject.
BELONGS_TO_A_SIBLING = (
    "coverage certificate",
    "per-caller budget",
    "rejection ledger",
    "look budget",
)

NEGATIONS = ("not ", "no ", "never ", "nothing ", "cannot ", "does not", "without ")


def sentences(text: str) -> list[str]:
    return [part.strip() for part in re.split(r"(?<=[.!?])\s+", " ".join(text.split()))]


@pytest.mark.parametrize("phrase", CLAIMS_TO_AVOID)
def test_the_page_never_claims_what_it_cannot_support(phrase: str) -> None:
    """THE CHECK IS ON THE CLAIM, NOT THE WORD, and the first version was on the word.

    It failed on this repository's own disclaimers, which are the sentences a word-level ban
    reaches first: the page says it is not an on-call rotation, an escalation policy or a paging
    provider, and that it does not monitor anything real. A ban that fires on the sentence
    saying no is a ban that pushes the disclaimer off the page, which is the opposite of what it
    is for.

    So every sentence containing one of these has to contain a negation as well.
    """
    for sentence in sentences(own_prose()):
        if phrase in sentence.lower():
            assert any(negation in sentence.lower() for negation in NEGATIONS), (
                f"this sentence claims {phrase!r} rather than denying it: {sentence!r}"
            )


@pytest.mark.parametrize("phrase", BELONGS_TO_A_SIBLING)
def test_the_page_does_not_use_a_siblings_vocabulary_at_all(phrase: str) -> None:
    """Banned outright: using a sibling phrase even to disclaim it describes its subject."""
    assert phrase not in own_prose().lower()


def test_the_page_names_the_registry_as_the_thing_a_reader_should_open() -> None:
    """The registry IS the monitoring, so it is what a reader should be sent to first."""
    first = " ".join(README.splitlines()[:45]).lower()
    assert "registry" in first
    assert "monitors.py" in first


def test_the_page_states_the_holiday_limitation() -> None:
    """No holiday calendar ships here, and the consequence belongs on the page."""
    flattened = " ".join(own_prose().split()).lower()
    assert "holiday" in flattened
    assert "trading day" in flattened
